/**
 * Garden ↔ Restaurant ↔ Shop Sync Service
 * Phase 2.5 - TEDSAI Admin Dashboard
 * 
 * Synchronisation automatique de l'écosystème
 */

export interface StockUpdate {
    productId: string;
    productName: string;
    oldQuantity: number;
    newQuantity: number;
    unit: 'kg' | 'units' | 'L';
    source: 'garden' | 'restaurant' | 'shop';
    timestamp: Date;
}

export interface AutoPromoConfig {
    productId: string;
    productName: string;
    currentStock: number;
    avgWeeklyConsumption: number;
    daysUntilExpiry: number;
    discountPercentage: number;
    urgency: 'low' | 'medium' | 'high';
}

/**
 * Règle 1 : Stock = 0 → Désactiver plats automatiquement
 */
export async function handleStockZero(update: StockUpdate): Promise<void> {
    if (update.newQuantity > 0) return;

    console.log(`[Sync] Stock à zéro détecté : ${update.productName}`);

    // TODO Phase 2.5: Chercher plats affectés en DB
    // const affectedDishes = await db.dishes.findWhere({
    //   ingredients: { contains: update.productId }
    // });

    // TODO Phase 2.5: Désactiver les plats
    // for (const dish of affectedDishes) {
    //   await db.dishes.update(dish.id, {
    //     availability: 'out_of_stock',
    //     publicStatus: 'hidden',
    //     reason: `Ingrédient "${update.productName}" en rupture`
    //   });
    // }

    // TODO Phase 2.5: Alerte urgente manager
    // await sendUrgentAlert({
    //   type: 'ingredient_unavailable',
    //   productName: update.productName,
    //   affectedDishes: affectedDishes.length,
    //   action: 'Commande fournisseur urgent ou récolte planifiée'
    // });

    console.log(`[Sync] Plats désactivés automatiquement (simulation)`);
}

/**
 * Règle 2 : Surplus → Promo anti-gaspillage automatique
 */
export async function checkAndCreateAutoPromo(
    productId: string
): Promise<AutoPromoConfig | null> {
    console.log(`[Sync] Vérification surplus pour produit ${productId}`);

    // TODO Phase 2.5: Récupérer données stock et consommation
    // const product = await db.gardenStock.findById(productId);
    // const avgConsumption = await getWeeklyAverage(productId);
    // const daysUntilExpiry = calculateFreshness(product);

    // Simulation
    const currentStock = 15; // kg
    const avgWeeklyConsumption = 8; // kg/semaine
    const daysUntilExpiry = 4; // jours

    // Critère : Stock > 150% consommation ET < 7j fraîcheur
    const surplusRatio = currentStock / avgWeeklyConsumption;

    if (surplusRatio > 1.5 && daysUntilExpiry <= 7) {
        const discount = daysUntilExpiry <= 3 ? 40 : 30;
        const urgency = daysUntilExpiry <= 3 ? 'high' : 'medium';

        const promoConfig: AutoPromoConfig = {
            productId,
            productName: 'Tomates Bio',
            currentStock,
            avgWeeklyConsumption,
            daysUntilExpiry,
            discountPercentage: discount,
            urgency,
        };

        // TODO Phase 2.5: Créer promo en DB
        // await db.promos.create({
        //   productId,
        //   discount: discount,
        //   startDate: new Date(),
        //   endDate: addDays(new Date(), daysUntilExpiry),
        //   reason: 'anti_waste',
        //   autoGenerated: true,
        // });

        console.log(`[Sync] Promo ${discount}% créée automatiquement`);
        return promoConfig;
    }

    return null;
}

/**
 * Règle 3 : Récolte → Suggestions menu automatiques
 */
export async function suggestMenuFromHarvest(
    harvestData: {
        productId: string;
        productName: string;
        quantity: number;
        quality: 'A' | 'B' | 'C';
    }
): Promise<string[]> {
    console.log(`[Sync] Nouvelle récolte : ${harvestData.productName} (${harvestData.quantity}kg)`);

    // TODO Phase 2.5: Appeler Gemini API pour suggestions plats
    // const suggestions = await geminiAPI.generateContent({
    //   prompt: `Tu es chef cuisinier camerounais. 
    //   Nous venons de récolter ${harvestData.quantity}kg de ${harvestData.productName} qualité ${harvestData.quality}.
    //   Suggère 3 plats fusion camerounais modernes à ajouter au menu.
    //   Format : Nom du plat | Ingrédients | Prix suggéré FCFA`
    // });

    // Simulation
    const suggestions = [
        'Ndolé 2.0 aux Tomates Bio | Ndolé, tomates, arachides | 3500 FCFA',
        'Salade Tropicale Croquante | Tomates, laitue, avocat | 2500 FCFA',
        'Sauce Tomate Maison Premium | Tomates, oignons, épices | 1500 FCFA',
    ];

    console.log(`[Sync] ${suggestions.length} suggestions générées`);
    return suggestions;
}

/**
 * Webhook handler pour events Garden
 */
export async function handleGardenEvent(event: {
    type: 'stock_update' | 'harvest' | 'expiry_alert';
    data: any;
}): Promise<void> {
    switch (event.type) {
        case 'stock_update':
            const update: StockUpdate = event.data;
            if (update.newQuantity === 0) {
                await handleStockZero(update);
            }
            await checkAndCreateAutoPromo(update.productId);
            break;

        case 'harvest':
            await suggestMenuFromHarvest(event.data);
            break;

        case 'expiry_alert':
            await checkAndCreateAutoPromo(event.data.productId);
            break;
    }
}
